### ISSUE TITLE
Support für PHP 7.2 ?

### ISSUE THREAD

**Issue by GreenDevil69** [DrOpossum/Teamspeak-Verifizierung#1]
hi, habe Teamspeak-Verifizierung auf meinem Server, wo auch noch webseiten laufen, habe gestern auf PHP 7.2 Upgedated. und jetzt funktioniert Teamspeak-Verifizierung garnichtmehr.
Zeigt nur noch eine Weisse seite an.

Ist ein update in Planung für PHP 7.2 ?

Mit Besten Grüssen :)

**Comment by FelixGerberding** [comment]
Hey GreenDevil69,

Einfach den Inhalt von libraries/TeamSpeak3 mit dem diesem Ordner hier ersetzen: https://github.com/planetteamspeak/ts3phpframework/tree/master/libraries/TeamSpeak3

Werde es demnächst auch hier integrieren, danke für die Melung. 

Mit freundlichen Grüßen,
Felix
